# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 13:02
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0002_auto_20171018_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='useritem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wear',
        ),
        migrations.AddField(
            model_name='user',
            name='item',
            field=models.ManyToManyField(to='apka.Item'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username'),
        ),
        migrations.DeleteModel(
            name='UserItem',
        ),
        migrations.AddField(
            model_name='case',
            name='item_list',
            field=models.ManyToManyField(to='apka.Item'),
        ),
    ]
